// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/klee/AndroidStudioProjects/Scout/core/src/main/java/com/nightscout/core/model/Download.proto
package com.nightscout.core.model;

import com.squareup.wire.ProtoEnum;

public enum GlucoseUnit
        implements ProtoEnum {
    MGDL(0),
    MMOL(1);

    private final int value;

    GlucoseUnit(int value) {
        this.value = value;
    }

    @Override
    public int getValue() {
        return value;
    }
}
