package org.nightscout.lasso.alarm;

import com.nightscout.core.dexcom.records.EGVRecord;
import com.nightscout.core.model.GlucoseUnit;

import java.util.List;

public interface AlarmStrategy {
    /**
     * Analyze egv records to determine if alarms are necessary and set messages
     *
     * @param egvRecords A list of {@link EGVRecord} sorted by date in ascending order
     * @param unit       Prefered unit for any messages that are generated by the strategy
     * @return {@link AlarmResults}
     */
    AlarmResults analyze(List<EGVRecord> egvRecords, GlucoseUnit unit);
}
